language: java
before_install:
  - cp dialoghandler/src/main/java/com/almende/dialog/Settings.java.example dialoghandler/src/main/java/com/almende/dialog/Settings.java
instal: mvn test -DskipTests=false
