language: java
sudo: false
before_install:
  - cp dialoghandler/src/main/java/com/almende/dialog/Settings.java.example dialoghandler/src/main/java/com/almende/dialog/Settings.java
script: mvn test -DskipTests=false
